### ISSUE TITLE
change background color

### ISSUE THREAD

**Issue by dzshi96** [nickgravgaard/ElasticNotepad#8]
I tried for a few hours and the environment keeps reporting errors。
After the jar runs, the theme background is black. Can you make a white-themed jar package?thank you very much
![image](https://user-images.githubusercontent.com/54979250/162720990-4bbe0a57-e7c6-48f8-a5e8-c7251cf0c493.png)

**Comment by nickgravgaard** [comment]
Hi there, it looks like those `ammonite.ops.*` functions have been deprecated. I just pushed a fix.

If you want to use a light theme, try importing `com.formdev.flatlaf.FlatIntelliJLaf` instead of `com.formdev.flatlaf.FlatDarculaLaf`, and then changing the `UIManager.setLookAndFeel` line accordingly. The code explicitly sets the background of the EditorTextPane, so you'll need to comment that out or change it to a colour of your choosing.

Let me know if you have any problems.

**Comment by dzshi96** [comment]
The theme modification is successful, thank you very much
![image](https://user-images.githubusercontent.com/54979250/164372908-9c031d3e-f000-42a3-8562-774c6c256441.png)
